name: Bug Report
description: File a bug report to help us improve the tool
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting your bug report
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have tested this issue on the latest version of the tool
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see happening
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Tell us what you expected to see
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: business-description
    attributes:
      label: Business Description Used
      description: If applicable, what business description or input data caused the issue?
      placeholder: "Example: Professional pet grooming services..."
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: What browser are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Opera
        - Other

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser are you using?
      placeholder: "Example: Chrome 118.0.5993.88"
    validations:
      required: false

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      multiple: false
      options:
        - Desktop
        - Tablet
        - Mobile
        - Other

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Any error messages or console output you see
      placeholder: Paste any error messages here
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, including screenshots if helpful
    validations:
      required: false