blank_issues_enabled: false
contact_links:
  - name: Live Demo
    url: https://kedster.github.io/AI-Powered-SEO-Keyword-Suggestion-Tool/
    about: Try the tool live to test functionality before reporting issues
  - name: Documentation
    url: https://github.com/kedster/AI-Powered-SEO-Keyword-Suggestion-Tool#readme
    about: Read the full documentation and setup guide