name: Feature Request
description: Suggest a new feature or enhancement for the AI-Powered SEO Keyword Tool
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible about your idea.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting your feature request
      options:
        - label: I have searched existing issues to make sure this feature hasn't been requested before
          required: true
        - label: This feature would benefit other users, not just my specific use case
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen
      placeholder: Describe the feature you'd like to see added
    validations:
      required: true

  - type: textarea
    id: problem-solving
    attributes:
      label: Problem it solves
      description: What problem does this feature solve? What need does it address?
      placeholder: Explain the problem or need this feature would address
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe your proposed solution in detail
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - AI/Keyword Generation
        - User Interface/Experience
        - SEO Analysis
        - Data Export/Import
        - Performance/Optimization
        - Accessibility
        - Mobile Experience
        - Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my use of the tool
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Example use case 1: ...
        Example use case 2: ...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or examples about the feature request
    validations:
      required: false